### ISSUE TITLE
Failing to write MSC mapping

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#58] opened 2020-05-22 06:53 UTC
Tested with [this mapping](https://coli-conc.gbv.de/cocoda/app/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F1940&toScheme=http%3A%2F%2Fmsc2010.org%2Fresources%2FMSC%2F2010%2Fmsc2010%2F&from=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ44455&to=http%3A%2F%2Fmsc2010.org%2Fresources%2FMSC%2F2010%2F91-XX&mapping=%7B%22from%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ44455%22,%22notation%22%3A%5B%22Q44455%22%5D%7D%5D%7D,%22to%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Fmsc2010.org%2Fresources%2FMSC%2F2010%2F91-XX%22,%22notation%22%3A%5B%2291-XX%22%5D%7D%5D%7D,%22fromScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F1940%22,%22notation%22%3A%5B%22WD%22%5D%7D,%22toScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Fmsc2010.org%2Fresources%2FMSC%2F2010%2Fmsc2010%2F%22,%22notation%22%3A%5B%22MSC%22%5D%7D,%22type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23narrowMatch%22%5D,%22identifier%22%3A%5B%22urn%3Ajskos%3Amapping%3Acontent%3A7bde1087ee3d468425ce1dbbecb26fcd7253d568%22,%22urn%3Ajskos%3Amapping%3Amembers%3A2637e67095ee2d9d461223da241a3106cd4cea20%22%5D%7D). May also be a configuration error?

**Comment by stefandesu** [comment] 2020-05-25 06:42
If you had tried any other mapping, or looked at the network response, you would have seen that it was an issue with our instance. First of all, I temporarily fixed it by installing the dependencies on our instance and restarting it. Here's the problem:
- `package-lock.json` is not included in this repository
- our instance gets updated automatically with every commit on master on this repo
- during the update, the script looks for a `package-lock.json` file; if there is one, it will run `npm ci`, if there isn't one, it will run `npm install`
- while the `package-lock.json` file is not committed in this repo, it will still be generated when running `npm install`, so at some point, our update script did that and we had a `package-lock.json` file
- so on the next update, the script detected that file and ran `npm ci`; but because the `package-lock.json` is not committed in the repository, the `package-lock.json` was not in sync with `package.json` and npm refused to install dependencies
- this caused an issue with our dependencies on the server and all requests failed

I see three different possibilities to fix this:
1. Include `package-lock.json` in this repo.
2. Adjust our server so that either `npm install` is used always, or that it checks whether `package-lock.json` is part of the repo and uses that to decided whether to use `npm install` or `npm ci`.
3. Use `npm install --no-package-lock` on the server so that a `package-lock.json` is never generated.

I'm voting for 1. `package-lock.json` is intended to be included in source control [by design](https://docs.npmjs.com/configuring-npm/package-lock-json.html). The arguments against using it are either not convincing or only refer to packages that are used as dependencies by other applications (so it doesn't apply to wikidata-jskos). I'm voting for including the file and always using `npm ci` to install dependencies, except if the purpose is to update the dependencies (because then the updated `package-lock.json` will be committed). 

I will still implement 3. because it fixes the immediate problem, but I'm also voting for 1. for all our projects. We have the `package-lock.json` file in source control in most of our repos anyway.

**Closed** 2020-05-25 06:54 UTC
Labels: bug

**Comment by nichtich** [comment] 2020-05-25 06:56
OK, include `package-lock.json` and make sure the docs tell to use `nmp ci`
